version: "3.8"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dalala
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/dalala.sql:/docker-entrypoint-initdb.d/dalala.sql:ro
    # Do not publish MySQL port to the host to avoid conflicts with a local MySQL server.
    # The `web` service connects to `db` via the Docker network.

  web:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:cached
    environment:
      DB_HOST: db
      DB_NAME: dalala
      DB_USER: root
      DB_PASS: ""
    ports:
      - "8000:80"

volumes:
  db_data:
